from .colours import red
from .colours import green
from .colours import yellow
from .colours import bold
from .colours import varName
from .colours import varType
from .colours import func
from .colours import file
from .colours import error
from .colours import success
from .colours import result
from .colours import clear
from .colours import warning
from .colours import arg
from .colours import inverse
from .colours import underline